version: '3'

services:
    nginx:
        container_name: plesanter_nginx
        image: nginx:1.19
        tty: true
        ports:
            - 80:80
        volumes: 
            - ./web/default.conf:/etc/nginx/conf.d/default.conf

    app:
        container_name: plesanter_app
        build: ./app
        tty: true
        ports: 
            - 5000:5000
        volumes: 
            - ./app/Rds.json:/web/Implem.Pleasanter/App_Data/Parameters/Rds.json
        environment:
            - TZ=Asia/Tokyo
            # - ASPNETCORE_URLS=https://+;http://+;
            # ↓一説によるとこれで直るらしいがローカルアクセスすら無理になる
            # - ASPNETCORE_URLS=http://+;
    db:
        container_name: plesanter_db
        image: postgres:12.3-alpine
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: plesanter
            POSTGRES_DB: Implem.Pleasanter
        volumes:
            - ./db:/var/lib/postgresql/data
